apiVersion: v1
kind: Service
metadata:
  name: app-kura-rasp
  labels:
    app: kura-rasp
spec:
  type: LoadBalancer 
  selector:
    app: kura-rasp
  ports:
    - port: 80 #on Host
      targetPort: http
      protocol: TCP