FROM python:3.5-slim

MAINTAINER HaiQuan "haiquan5396@gmail.com"

ENV BROKER_CLOUD localhost
ENV BROKER_FOG locahost

COPY Fog/Forwarder/requirements.txt /app/requirements.txt

COPY Performance_Monitoring/message_monitor.py /app/Performance_Monitoring/message_monitor.py

WORKDIR /app

RUN pip3 install -r requirements.txt

COPY Fog/Forwarder/Forwarder_Fog_to_Cloud.py /app

CMD python3 Forwarder_Fog_to_Cloud.py ${BROKER_CLOUD} ${BROKER_FOG}

#docker build -t haiquan5396/forwarder_fog_to_cloud:1.2 -f Dockerfile_Fog_to_Cloud .
#docker run -it --name fog-cloud-test -e "BROKER_CLOUD=192.168.60.248" -e "BROKER_FOG=192.168.60.248" haiquan5396/forwarder_fog_to_cloud:1.2